# Generated by Django 3.0.6 on 2020-07-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름을 입력하세요.', max_length=15)),
                ('summ', models.TextField(default='설명을 입력하세요.')),
            ],
        ),
    ]
