# Generated by Django 3.0.8 on 2020-07-30 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plc', models.CharField(default='보관장소', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'test_user',
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='image')),
                ('name', models.CharField(default='이름', max_length=15)),
                ('amount', models.IntegerField(default='0')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('exp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.category')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
