# Generated by Django 3.0.8 on 2020-07-30 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='plc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app0.category'),
        ),
    ]
