# Generated by Django 3.0.6 on 2020-07-19 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=15)),
                ('amount', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('exp', models.DateTimeField()),
                ('plc', models.CharField(default='보관장소', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='summ',
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='exp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='plc',
            field=models.CharField(default='보관장소', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='이름', max_length=15),
        ),
    ]
