# Generated by Django 3.0.8 on 2020-07-23 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0002_auto_20200720_0332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='Plc',
            field=models.CharField(default='보관장소', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='exp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='plc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.category'),
        ),
    ]
