# Generated by Django 3.0.8 on 2020-07-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0004_auto_20200724_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.CharField(blank=True, default=1, max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='item',
            name='exp',
            field=models.DateField(blank=True, default='2020-01-01'),
        ),
    ]
