# Generated by Django 3.0.8 on 2020-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0005_auto_20200724_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='item',
            name='exp',
            field=models.DateTimeField(blank=True, default='2020-01-01'),
        ),
    ]
