# Generated by Django 3.0.8 on 2020-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0006_auto_20200724_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, default='2020-01-01'),
        ),
    ]
