# Generated by Django 3.0.8 on 2020-07-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0007_auto_20200724_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exp',
            field=models.DateField(blank=True, default='2020-01-01'),
        ),
    ]
