# Generated by Django 3.0.8 on 2020-07-24 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0009_auto_20200724_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
