# Generated by Django 3.0.6 on 2020-07-25 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0010_auto_20200724_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='plc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.category'),
        ),
    ]
