# Generated by Django 3.0.6 on 2020-07-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0011_auto_20200725_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
