# Generated by Django 3.0.6 on 2020-07-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0014_auto_20200726_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='plc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.category'),
        ),
    ]
