# Generated by Django 3.0.6 on 2020-07-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0015_auto_20200726_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
    ]
