# Generated by Django 3.0.6 on 2020-07-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0016_auto_20200726_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['date']},
        ),
    ]
