# Generated by Django 3.0.6 on 2020-07-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0019_auto_20200730_1007'),
        ('app0', '0011_auto_20200729_1720'),
    ]

    operations = [
    ]
